#阿里云短信配置
#申请地址 https://dysms.console.aliyun.com

sms:
  #根据项目修改
  #阿里云 AccessKey ID
  access_key_id: LTAIevctXMoHxG3j
  #阿里云 Access Key Secret  
  access_key_secret: BBODv7ugOOZKdXaGSd0rZmthZxXwtp
  #阿里云签名
  sign_name: 壹壹优选
  
  #以下为基础配置 无需修改
  #短信API产品名称（短信产品名固定，无需修改）
  product: Dysmsapi
  #短信API产品域名（接口地址固定，无需修改）
  domain: dysmsapi.aliyuncs.com
  #地区
  region_id: cn-hangzhou
  #端点名称
  endpoint_name: cn-hangzhou
  #连接超时 key
  connect_timeout_key: sun.net.client.defaultConnectTimeout
  #读取超时 key
  read_timeout_key: sun.net.client.defaultReadTimeout
  #连接超时 value
  default_connect_timeout: 10000
  #读取超时 key
  default_read_timeout: 10000
  #发送成功状态
  send_success: OK
  
  
  