#微信配置
wechat:
  #微信服务号配置
  mp_app_id: wx624636d7fc542eb3
  mp_app_secret: 5435337998a3b45cd31d0677a933df29
  mp_mch_id: 1466953202
  mp_partner_key: jiuziqi412724198512143712yiyiyou
  #基础配置
  mp_oauth_grant_type: authorization_code
  mp_token_url: https://api.weixin.qq.com/cgi-bin/token
  mp_jsapi_ticket_url: https://api.weixin.qq.com/cgi-bin/ticket/getticket
  mp_access_token_url: https://api.weixin.qq.com/sns/oauth2/access_token
  mp_refresh_token_url: https://api.weixin.qq.com/sns/oauth2/refresh_token
  mp_userinfo_url: https://api.weixin.qq.com/sns/userinfo
  #回调方法
  mp_test_notify_url: http://test.app.my11mall.com/wechat/weChatNotifyForMp
  mp_prod_notify_url: http://app.my11mall.com/wechat/weChatNotifyForMp
  #回调方法
  app_test_notify_url: http://test.app.my11mall.com/wechat/weChatNotifyForApp
  app_prod_notify_url: http://app.my11mall.com/wechat/weChatNotifyForApp
  
  #微信APP配置
  app_id: wx95cce4bd957b05ad
  app_secret: 27c55a83ae52140d36e6e2d4a95b5b7a
  app_mch_id: 1516922611
  app_partner_key: jiuziqi412724198512143712yiyiyou
  partner_id: gh_cd523d28ad67
  grant_type: client_credential
  unified_order_url: https://api.mch.weixin.qq.com/pay/unifiedorder
  close_order_url: https://api.mch.weixin.qq.com/pay/closeorder
  order_query_url: https://api.mch.weixin.qq.com/pay/orderquery
  app_access_token_url: https://api.weixin.qq.com/sns/oauth2/access_token
  app_check_access_token_url: https://api.weixin.qq.com/sns/auth
  app_userinfo_url: https://api.weixin.qq.com/sns/userinfo
  app_grant_type: authorization_code
  
  